name: Goreleaser to GH releases and brew tap

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.4'
          cache: true
        id: go

      - name: Unshallow git repo
        run: git fetch --prune --unshallow

      - name: Run goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        run: make goreleaser-release
